/* eslint-disable import/prefer-default-export */
export const ASSISTANT = {
    SET_ASSISTANT_NAME: '@@SIGN_UP/SET_ASSISTANT_NAME',
    SET_ASSISTANT_GENDER: '@@SIGN_UP/SET_ASSISTANT_GENDER',
    SET_ASSISTANT_COLOR: '@@SIGN_UP/SET_ASSISTANT_COLOR',
    SET_ASSISTANT_ICON_FILE_NAME: '@@SIGN_UP/SET_ASSISTANT_ICON_FILE_NAME',
};
