export const ACTION_STATUSES = {
    UNDEFINED: 'undefined',
    PENDING: 'pending',
    SUCCESS: 'success',
    FAIL: 'fail',
};

export const ASSISTANT = {
    SET_ASSISTANT_NAME: '@@ASSISTANT/SET_ASSISTANT_NAME',
    SET_ASSISTANT_GENDER: '@@ASSISTANT/SET_ASSISTANT_GENDER',
    SET_ASSISTANT_COLOR: '@@ASSISTANT/SET_ASSISTANT_COLOR',
    SET_ASSISTANT_ICON_FILE_NAME: '@@ASSISTANT/SET_ASSISTANT_ICON_FILE_NAME',
};

export const PROFILE = {
    SET_PROFILE_INFO: '@@PROFILE/SET_PROFILE_INFO',
};

export const SIGN_UP = {
    ATTEMPT_SIGN_UP: '@@SIGN_UP/ATTEMPT_SIGN_UP',
    SET_SIGN_UP_ACTION_STATUS: '@@SIGN_UP/ATTEMPT_SIGN_UP_ACTION_STATUS',
};

export const SIGN_IN = {
    ATTEMPT_SIGN_IN: '@@SIGN_IN/ATTEMPT_SIGN_IN',
    SET_SIGN_IN_ACTION_STATUS: '@@SIGN_IN/ATTEMPT_SIGN_IN_ACTION_STATUS',
};
